-- USERS
INSERT INTO user(username,password,role,first_name,last_name,email,is_pw,accept_terms,confirm_pw,emailcorrect) VALUES ('admin','$2a$10$j8kKMynCBacALgRZvdtU2ezRo8cZJUash26OOUBBXsfzTTj/Xt5vG', 'ROLE_ADMIN','Test', 'Test',  'email@email.com', true ,true, '$2a$10$j8kKMynCBacALgRZvdtU2ezRo8cZJUash26OOUBBXsfzTTj/Xt5vG',true);
INSERT INTO user(username,password,role,first_name,last_name,email,is_pw,accept_terms,confirm_pw,emailcorrect) VALUES ('user','$2a$10$wzVJFOPkNz410shGyVcHseQDnHKNKuKCphIr1iLj4Xw.Bvrgce3ai', 'ROLE_USER','Test', 'Test',  'email@email.com', true ,true, '$2a$10$wzVJFOPkNz410shGyVcHseQDnHKNKuKCphIr1iLj4Xw.Bvrgce3ai',true);

-- CATEGORIES
INSERT INTO category (name) VALUES ('Traditional');
INSERT INTO category (name) VALUES ('Vegetarian');
INSERT INTO category (name) VALUES ('Vegan');

INSERT INTO category (name) VALUES ('Antipasti');
INSERT INTO category (name) VALUES ('Pasta');
INSERT INTO category (name) VALUES ('Sandwiches');
INSERT INTO category (name) VALUES ('Wraps');
INSERT INTO category (name) VALUES ('FastFood');
INSERT INTO category (name) VALUES ('Bowls');
INSERT INTO category (name) VALUES ('Asian');

INSERT INTO category (name) VALUES ('Dessert');
INSERT INTO category (name) VALUES ('Salad');


-- RECIPES

-- TRADITIONAL
INSERT INTO lazyrecipes.recipe (id, date, ingredients, likes, portions, prep_time, ratingavg, steps, subtitle, title, category_id, user_id) VALUES (1, '2021-06-24', '- 2 tablespoons bacon grease\r\n- 1 medium sweet onion, finely diced\r\n- 1 clove garlic, minced\r\n- 4 cups chicken broth\r\n- 1 (28-ounce) can petite diced tomatoes, undrained\r\n- 2 cups long grain white rice\r\n- 1/2 teaspoon salt', null, 1, 30, null, '- In a large pot with a tight fitting lid, melt the bacon grease over medium high heat. \r\n- Add the onions and cook until translucent and tender. \r\n- Add the garlic and cook for 1 minute.\r\n- Add the chicken broth and tomatoes. \r\n- Bring to a boil. \r\n- Add the rice and stir well. \r\n- Add salt to taste. \r\n- Reduce the heat to a low simmer and cover. \r\n- Cook for 20 to 25 minutes or until tender and most of the liquid has been absorbed. \r\n- Turn off the heat and allow the rice to rest for an additional 5 minutes to allow the remaining liquid to be absorbed. \r\n- Fluff the rice with a fork and serve.', 'Takes plain ol’ white rice from ordinary to extraordinary!', 'Rice with Tomatoes', 1, 1);

-- VEGETARIAN

-- VEGAN
INSERT INTO lazyrecipes.recipe (id, date, ingredients, likes, portions, prep_time, ratingavg, steps, subtitle, title, category_id, user_id) VALUES (2, '2021-06-24', '- 1 tablespoon olive oil\r\n- 1 medium white onion chopped\r\n- 4 teaspoons minced garlic see note\r\n- 1 tablespoon unsalted butter\r\n- 1 teaspoon soy sauce\r\n- 8 oz fresh spinach\r\n- 1/2 teaspoon salt\r\n- 1/4 teaspoon black pepper', null, 1, 9, null, '- In a large skillet, heat up olive oil.\r\n- Add onion and saute for 4 minutes.\r\n- Add garlic and butter and saute until the onion is starting to brown.\r\n- Add soy sauce and stir well.\r\n- Add spinach and gently toss to mix with sauteed onion.\r\n- Cook until spinach is wilted.\r\n- Season with salt and pepper.\r\n- Serve immediately.', 'Easiest and fastest spinach side dish', 'Spinach', 3, 1);

-- ANTIPASTI
INSERT INTO lazyrecipes.recipe (id, date, ingredients, likes, portions, prep_time, ratingavg, steps, subtitle, title, category_id, user_id) VALUES (3, '2021-06-24', '- olive oil, divided\r\n- 5 zucchinis, thinly sliced lengthwise\r\n- 1 (4 ounce) package crumbled feta cheese\r\n- 3 cloves garlic, minced\r\n- 2 tablespoons dried Italian herbs\r\n- 4 tablespoons balsamic vinegar', null, 6, 20, null, '- Heat 2 tablespoons olive oil in a large skillet and cook zucchini slices in batches until soft and lightly browned on both sides, 5 to 10 minutes.\r\n- Add more olive oil as needed.\r\n- Remove zucchini slices from skillet and drain on paper towels.\r\n- Sprinkle zucchini slices with feta and roll up.\r\n- Secure each roll with a tooth pick.\r\n- Set zucchini rolls into a dish that is as deep as the rolls are high, and sprinkle with garlic, Italian herbs, and balsamic vinegar.\r\n- Cover and marinate in the refrigerator for 1 to 2 days.', 'These vegetarian antipasti rolls with zucchini and feta are ideal for a party because you can make them a couple of days before. ', 'Zucchini-Feta Rolls', 4, 1);

-- PASTA
Insert INTO lazyrecipes.recipe (id, date, ingredients, likes, portions, prep_time, ratingavg, steps, subtitle, title, category_id, user_id) VALUES (8, '2021-06-24', '- 1 tbsp oliveoil\r\n- 4 rashers smoked streaky bacon, finely chopped\r\n- 2 medium onions, finely chopped\r\n- 2 carrots, trimmed and finely chopped\r\n- 2 celery sticks, finely chopped\r\n- 2 garlic cloves finely chopped\r\n- 2-3 sprigs rosemary leaves picked and finely chopped\r\n- 500g beef mince', null, 2, 35, null, 'STEP 1\r\nPut a large saucepan on a medium heat and add 1 tbsp olive oil.\r\n\r\nSTEP 2\r\nAdd 4 finely chopped bacon rashers and fry for 10 mins until golden and crisp.\r\n\r\nSTEP 3\r\nReduce the heat and add the 2 onions, 2 carrots, 2 celery sticks, 2 garlic cloves and the leaves from 2-3 sprigs rosemary, all finely chopped, then fry for 10 mins. Stir the veg often until it softens.\r\n\r\nSTEP 4\r\nIncrease the heat to medium-high, add 500g beef mince and cook stirring for 3-4 mins until the meat is browned all over.\r\n\r\nSTEP 5\r\nAdd 2 tins plum tomatoes, the finely chopped leaves from ¾ small pack basil, 1 tsp dried oregano, 2 bay leaves, 2 tbsp tomato purée, 1 beef stock cube, 1 deseeded and finely chopped red chilli (if using), 125ml red wine and 6 halved cherry tomatoes. Stir with a wooden spoon, breaking up the plum tomatoes.\r\n\r\nSTEP 6\r\nBring to the boil, reduce to a gentle simmer and cover with a lid. Cook for 1 hr 15 mins stirring occasionally, until you have a rich, thick sauce.\r\n\r\nSTEP 7\r\nAdd the 75g grated parmesan, check the seasoning and stir.\r\n\r\nSTEP 8\r\nWhen the bolognese is nearly finished, cook 400g spaghetti following the pack instructions.', 'a classic', 'Spaghetti Bolognese', 5, 1);

-- SANDWICHES
INSERT INTO lazyrecipes.recipe (id, date, ingredients, likes, portions, prep_time, ratingavg, steps, subtitle, title, category_id, user_id) VALUES (7, '2021-06-24', '- 2 eggs\r\n- 2 tbsp mayonnaise\r\n- 3 slices bread\r\n- a little butter\r\n- ? carton of cress\r\n- 2-3 slices of tomato or a lettuce leaf and a slice of ham or cheese\r\n- crisps , to serve', null, 1, 20, null, 'STEP 1\r\nBring a pan of water to the boil and carefully lower in the eggs. Cook for 6 mins, then cool under running water until they can be peeled. Peel the eggs, then leave to cool completely.\r\n\r\nSTEP 2\r\nMash or chop the eggs, then mix with 1½ tbsp mayonnaise and some seasoning, if you like. Toast the bread.\r\n\r\nSTEP 3\r\nLay one slice of bread on a board. Butter it, then spread on three quarters of the egg and scatter over the cress. Add another slice of toast and gently spread on the remaining mayo. Add the tomato or lettuce and ham or cheese (or whichever combination you prefer). Dot the remaining egg over the top, spread gently, then top with the final piece of toast. Cut the crusts off if you like, then gently cut the sandwich into four quarters, being careful not to squash out the egg. Skewer each sandwich with a sandwich pick. Serve with crisps.', 'best choice for a summer family picnic', 'Egg & cress club sandwich', 6, 1);
-- WRAPS

-- FAST FOOD
INSERT INTO lazyrecipes.recipe (id, date, ingredients, likes, portions, prep_time, ratingavg, steps, subtitle, title, category_id, user_id) VALUES (5, '2021-06-24', '- 1 kg / 2 lb chicken thighs , skinless and boneless (Note 1)\r\n- Olive oil , for drizzling\r\n- 1 cup plain yoghurt , unsweetened (I use Greek)\r\n- 3 garlic cloves minced\r\n- 1 1/2 tsp coriander powder\r\n- 2 tsp cumin powder\r\n- 2 tsp paprika\r\n- 1 tsp cayenne pepper , optional\r\n- 1 1/2 tsp onion powder\r\n- 1/2 tsp black pepper\r\n- 2 1/2 tbsp tomato paste\r\n- 1 1/2 tsp salt\r\n- 1 tbsp lemon juice\r\n- 2 tbsp olive oil', null, 1, 60, null, '- Mix Marinade in a large bowl.\r\n- Add chicken and mix to coat well.\r\n- Cover and marinate in the fridge for a minimum of 3 hours, 24 hours is ideal.\r\n- If only 3 hours, add an extra 1/2 tsp salt.\r\n- Preheat oven to 220C / 430F (standard) or 200C / 390F (fan / convection).\r\n- Choose a pan of a size such that the skewers will stay propped up on the pan walls (see photos in post or video) and the chicken will be elevated off the base.\r\n- Line with foil.\r\n- Remove chicken from fridge.\r\n- Divide the chicken into 2 piles.\r\n- Take one piece of chicken, fold in half then thread onto two skewers (see video).\r\n- Repeat and push the chicken snugly up against each other.\r\n- Repeat with other skewer.\r\n- Prop the 2 skewers on the edges of the baking pan.\r\n- Drizzle surface with oil.\r\n- Bake for 35 minutes or until the surface is golden with some charred bits (char is good!).\r\n- Spoon the pan juices over the chicken.\r\n- Then turn, drizzle with oil and bake for 20 minutes (or 25 - 30 minutes if you had large thighs).\r\n- If you need / want more colour, switch to grill/broil for a few minutes on high.\r\n- Baste again with pan juices and stand for 5 minutes.\r\n- Carving: Stand the skewers upright or on an angle, and slice meat fairly thinly.', 'Kebab', 'Döner', 8, 1);
INSERT INTO lazyrecipes.recipe (id, date, ingredients, likes, portions, prep_time, ratingavg, steps, subtitle, title, category_id, user_id) VALUES (6, '2021-06-24', 'Homemade Pizza Dough:\r\n - 2 and 1/2 cups (300 grams) unbleached all-purpose flour\r\n - 1 teaspoon granulated sugar\r\n - 1/2 teaspoon active dry yeast (or SAF instant yeast)\r\n - 3/4 teaspoon kosher salt\r\n - 7 ounces warm water (105 degrees F – 115 degrees F)\r\n - 1 tablespoon extra virgin olive oil\r\n- 2 tablespoons semolina or all-purpose flour, for the pizza peel (divided)\r\nPizza Sauce:\r\n - 1 cup pureed or crushed San Marzano (or Italian plum) canned tomatoes\r\n - 2-3 fresh garlic cloves, minced with a garlic press\r\n - 1 teaspoon extra virgin olive oil, plus more for drizzling\r\n - 1/4 teaspoon freshly ground black pepper\r\n - 2-3 large pinches of kosher salt', null, 1, 30, null, 'Prepare Pizza Dough: In a medium bowl, whisk together the all-purpose flour, sugar, yeast and salt. Add the warm water and olive oil, and stir the mixture with a wooden spoon until the dough just begins to come together. It will seem shaggy and dry, but don’t worry.\r\nScrape the dough onto a well-floured counter top and knead the dough for three minutes. It should quickly come together and begin to get sticky. Dust the dough with flour as needed (sometimes I will have to do this 2 to 3 times, depending on humidity levels) – it should be slightly tacky, but should not be sticking to your counter top.  After three minutes, the dough should be smooth, slightly elastic, and tacky. Lightly grease a large mixing bowl with olive oil, and place the dough into the bowl.\r\nCover the bowl with a kitchen towel (or plastic wrap) and allow the dough to rise in a warm, dry area of your kitchen for 2 hours or until the dough has doubled in size. If your kitchen is very cold, one great tip that I do all the time is to heat a large heatproof measuring cup of water in the microwave for 2-3 minutes. This creates a nice warm environment and I’ll immediately remove the cup and place the bowl with the dough in the microwave until it has risen. [If you are preparing in advance, see the note section for freezing instructions.]', 'the best homemade margherita pizza', 'Margherita Pizza', 8, 1);
-- BOWLS

-- ASIAN

-- DESSERT
Insert INTO lazyrecipes.recipe (id, date, ingredients, likes, portions, prep_time, ratingavg, steps, subtitle, title, category_id, user_id) VALUES (4, '2021-06-24', '- 1 1/2 cups all-purpose flour\r\n- 1 1/2 tsp baking powder\r\n- 1 Tbsp lemon zest\r\n- 1/2 tsp salt\r\n- 1/2 cup unsalted butter, room temperature\r\n- 1 cup granulated sugar\r\n- 2 large eggs, room temperature\r\n- 1 tsp vanilla extract\r\n- 2 Tbsp lemon juice, about 1/2 lemon\r\n- 1/2 cup buttermilk', null, 1, 45, null, 'Preheat oven to 350°F (177°C). Grease a 9x5-inch (or 8x4-inch) loaf pan.\r\nIn a medium bowl combine the flour, baking powder, lemon zest, and salt. Set aside.\r\nIn the bowl of a stand mixer fitted with the paddle attachment (or using an electric mixer), cream the butter and sugar together at medium-high speed until pale and fluffy, about 4-6 minutes. Scrape the sides of the bowl as needed.\r\nWith the mixer running on low-speed, add the eggs one at a time, then beat in the vanilla extract and lemon juice. Beat on medium-high speed until combined.\r\nWith the mixer on low, add about one-third of the flour mixture and mix until almost combined, then add half the buttermilk and mix until just combined. Repeat with another third of flour mixture and then the last half of the buttermilk, ending with the last third of the flour. Beat until just incorporated.\r\nScrape the batter into the prepared loaf pan and bake for 45-55 minutes until the cake is golden brown and a toothpick comes out mostly clean with only a couple moist crumbs. Baking times vary, so keep an eye on yours.\r\nLet the cake cool for about 15 minutes in the pan. Stir together the lemon juice and confectioners’ sugar for the lemon syrup. Carefully invert the loaf pan, and transfer the cake to a cooling rack, then brush the syrup on the cake while it’s still warm. Allow cake to cool completely.\r\nWhen the cake is cooled, combine all the icing ingredients, start with 1 tbsp lemon juice and milk and add the remaining lemon juice as needed. The icing should be thick and not runny. Pour icing over cake and let dry before serving.', 'fluffy, tangy and so easy!', 'Lemon Cake', 11, 1);

-- SALAD


-- file
INSERT INTO lazyrecipes.file (id, content_type, original_file_name, size) VALUES (1, 'image/jpeg', 'external-content.duckduckgo.com2.jpg', 560811);
INSERT INTO lazyrecipes.file (id, content_type, original_file_name, size) VALUES (2, 'image/jpeg', 'external-contesnt.duckduckgo.com.jpg', 30746);
INSERT INTO lazyrecipes.file (id, content_type, original_file_name, size) VALUES (3, 'image/jpeg', 'rice.jpg', 326435);
INSERT INTO lazyrecipes.file (id, content_type, original_file_name, size) VALUES (4, 'image/jpeg', 'external-content.duckduckgo.com.jpg', 190483);
INSERT INTO lazyrecipes.file (id, content_type, original_file_name, size) VALUES (5, 'image/webp', 'image.webp', 84428);
INSERT INTO lazyrecipes.file (id, content_type, original_file_name, size) VALUES (6, 'image/webp', 'egg-cress-club-sandwich-9d415c2.webp', 27496);
INSERT INTO lazyrecipes.file (id, content_type, original_file_name, size) VALUES (7, 'image/jpeg', 'external-content.duckduckgo.com.jpg', 29078);
INSERT INTO lazyrecipes.file (id, content_type, original_file_name, size) VALUES (8, 'image/jpeg', 'P043_Margherita-main.jpg', 215562);
INSERT INTO lazyrecipes.file (id, content_type, original_file_name, size) VALUES (9, 'image/jpeg', '3D21E99D-71D0-4D3C-9418-DA0513C508BF.jpg', 78030);
-- recipe_files
INSERT INTO lazyrecipes.recipe_files (recipe_id, files_id) VALUES (8, 1);
INSERT INTO lazyrecipes.recipe_files (recipe_id, files_id) VALUES (8, 2);
INSERT INTO lazyrecipes.recipe_files (recipe_id, files_id) VALUES (1, 3);
INSERT INTO lazyrecipes.recipe_files (recipe_id, files_id) VALUES (2, 4);
INSERT INTO lazyrecipes.recipe_files (recipe_id, files_id) VALUES (3, 5);
INSERT INTO lazyrecipes.recipe_files (recipe_id, files_id) VALUES (7, 6);
INSERT INTO lazyrecipes.recipe_files (recipe_id, files_id) VALUES (5, 7);
INSERT INTO lazyrecipes.recipe_files (recipe_id, files_id) VALUES (6, 8);
INSERT INTO lazyrecipes.recipe_files (recipe_id, files_id) VALUES (4, 9);